url: https://ankitkachru.github.io
baseurl: ../portfolio2/

# Site settings
title: Ankit Kachroo
email: hello@ankitkachru.xyz
description: "Ankit Kachroo"


# Team names, titles and social links
people:
- name: Ankit Kachroo
  pic: 1
  position: 
  social:
    - title: twitter
      url: http://twitter.com/ankitkachru#
    - title: facebook
      url: http://facebook.com/ankitkachru#
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ankitkachru
  - title: facebook
    url: http://facebook.com/ankitkachru
  - title: github
    url: http://github.com/ankitkachru
  - title: linkedin
    url: http://linkedin.com/in/ankitkachru

# Postal address (add as many lines as necessary)
address:
  - line: 39/4 Pamposh Colony, Janipur
  - line: Jammu, JK, IN 180007

# Build settings
markdown: kramdown
permalink: pretty
